2020-02-07 02:10:50,108 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-02-07 02:11:43,548 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-02-07 02:27:40,304 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/ashoka/Documents/tattle_bot/venv/lib/python3.6/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "prototype.py", line 23, in echo
    context.bot.send_message(chat_id=update.effective_chat.id, text=update.message.text)
AttributeError: 'NoneType' object has no attribute 'text'
2020-02-07 02:28:02,110 - telegram.utils.promise - ERROR - An uncaught error was raised while running the promise
Traceback (most recent call last):
  File "/home/ashoka/Documents/tattle_bot/venv/lib/python3.6/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "prototype.py", line 23, in echo
    context.bot.send_message(chat_id=update.effective_chat.id, text=update.message.text)
AttributeError: 'NoneType' object has no attribute 'text'
2020-02-07 02:29:50,226 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-02-07 02:34:25,133 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-02-07 02:35:33,212 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-02-07 02:49:23,069 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2020-02-07 11:58:33,690 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
